
language: java

sudo: false


services:
  - docker


notifications:
  slack:
    iosr-workgroup:8wdjZUlR1MD3XQN16znNltRq#miosr_crud


script:
  mvn clean validate package


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t wzagrajcz/miosr-users -f Dockerfile .;
      docker login -u "$DOCKER_USERNAME_WZ" -p "$DOCKER_PASSWORD_WZ";
      docker push wzagrajcz/miosr-users;
    fi